# -*- coding: utf-8 -*-
"""
Bilingual Localization Engine (English & Bengali / বাংলা)
Provides natural, culturally accurate translations for UI, navigation,
threat types, possible consequences, and cybersecurity recommendations.
"""

TRANSLATIONS = {
    'en': {
        # Brand & Nav
        'brand_title': 'Email Sentinel AI',
        'brand_subtitle': 'SPAM & CYBER THREAT ANALYZER',
        'nav_scan': 'Scan Message',
        'nav_dashboard': 'Security Dashboard',
        'nav_history': 'Audit History',
        'nav_contacts': 'Trusted Contacts',
        'nav_signin': 'Sign In',
        'nav_register': 'Register',
        'nav_logout': 'Sign Out',
        'db_status_label': 'DB',

        # Hero
        'hero_badge': 'Multi-Vector Neural Protection Engine',
        'hero_title': 'AI-Powered Spam & Cyber Threat Analysis',
        'hero_desc': 'Detect phishing emails, smishing SMS, malicious links, and phone fraud with state-of-the-art AI. Autonomously recognizes personal messages from friends without false alarms.',
        
        # Tabs & Modes
        'tab_email': 'Email Mode',
        'tab_sms': 'SMS / Phone Mode',
        'presets_label': 'Try Real-World Threat Scenarios:',
        'preset_bank_phish': '1. Urgent Bank Phishing',
        'preset_power_smish': '2. Electricity Cut Smishing',
        'preset_lottery': '3. Lottery Advance-Fee Scam',
        'preset_friend_chat': '4. Friend Chat (Urgent Call)',
        'preset_legit_email': '5. Legitimate Work Email',

        # Form Inputs
        'lbl_sender': 'Sender Identifier (Email Address or Phone Number)',
        'lbl_subject': 'Subject Line',
        'lbl_content': 'Message Content',
        'sender_placeholder_email': 'e.g. security-alert@secure-bank-verify.com',
        'sender_placeholder_sms': 'e.g. +91 98765 43210 or VK-HDFCBK',
        'sender_tip_email': 'Legitimate institution or personal email',
        'sender_tip_sms': 'Standard 10-digit mobile number or TRAI SMS Header (e.g. AD-SBIINB)',
        'subject_placeholder': 'e.g. URGENT: Verify your account immediately',
        'content_placeholder': 'Paste the raw body text of the email or SMS here...',
        'autonomous_sensing_banner': 'Autonomous AI Intent Sensing:',
        'autonomous_sensing_desc': 'Automatically differentiates casual friend/family chats from scam pressure tactics without requiring manual contact entry.',
        'preverified_contact_opt': 'Pre-verified Contact (Optional)',
        'btn_analyze_email': 'Analyze Email Threat',
        'btn_analyze_sms': 'Analyze SMS Threat',
        'scan_footer_note': 'Scans Text Semantics, Embedded URLs, and Phone/WhatsApp Callback Vectors.',

        # Feature Cards
        'card_sms_title': 'SMS Smishing Detection',
        'card_sms_desc': 'Identifies fake electricity disconnections, PAN/KYC blocks, and personal mobile impersonations.',
        'card_phone_title': 'Phone Callback Defense',
        'card_phone_desc': 'Flags urgent vishing numbers, foreign carrier risks, and WhatsApp redirections.',
        'card_url_title': 'Suspicious URL Defense',
        'card_url_desc': 'Dissects IP addresses, domain age, credential phishing paths, and trojan executable payloads.',
        'card_risk_title': 'Risk Quantification',
        'card_risk_desc': 'Combines lexical NLP probabilities with external cyber vectors to deliver actionable safety verdicts.',

        # Result Page
        'report_title': 'Threat Analysis Report',
        'report_subtitle': 'Comprehensive multi-vector security assessment generated by Sentinel AI',
        'btn_back_scan': 'Scan Another Message',
        'verdict_title': 'Security Verdict',
        'spam_probability_label': 'Spam Probability',
        'overall_risk_title': 'Overall Risk Level',
        'threat_meter_title': 'Multi-Vector Threat Meter',
        'meter_safe': '0% Safe',
        'meter_danger': '100% Critical Danger',

        # Result Details
        'threat_type_title': 'Predicted Threat Type',
        'consequence_title': 'Possible Consequences',
        'recommendation_title': 'Security Recommendation',
        'msg_details_title': 'Message Technical Details',
        'col_property': 'Property',
        'col_value': 'Value',
        'prop_type': 'Communication Type',
        'prop_sender': 'Sender',
        'prop_subject': 'Subject',
        'prop_urls': 'Embedded Links',
        'prop_phones': 'Phone / WhatsApp Numbers',
        'prop_ai_override': 'AI Sense Override',
        'none_detected': 'None detected',
        'raw_content_title': 'Raw Message Text',

        # URL & Phone Cards
        'urls_analyzed_title': 'Embedded URLs Analyzed',
        'phones_analyzed_title': 'Embedded Phone Numbers Analyzed',
        'col_url': 'URL',
        'col_url_risk': 'URL Risk',
        'col_category': 'Threat Category',
        'col_reasons': 'Detected Indicators',
        'col_phone': 'Phone Number',
        'col_country': 'Country / Origin',
        'col_phone_type': 'Type',
        'col_phone_risk': 'Risk Level',

        # Banners
        'badge_ai_personal': 'AI Personal Sense',
        'banner_ai_personal': 'Autonomous AI Detection: Identified personal conversational tone, peer language, and everyday informal context without institutional threat or phishing cues.',
        'banner_whitelist': 'Verified Known Person: Sender is on your trusted whitelist. Conversational phrasing approved as safe.',
        'whitelisted_badge': 'Whitelisted',
        'feedback_prompt': 'Is this someone you know (friend, family, or colleague)?',
        'btn_mark_safe': 'Mark as Known Person (Not Spam)',

        # Contacts Page
        'contacts_title': 'Trusted Contacts & Whitelist',
        'contacts_subtitle': 'Messages from saved contacts are recognized as safe and conversational phrases will not trigger false alarms.',
        'add_contact_title': 'Add Trusted Contact',
        'lbl_contact_name': 'Contact Name / Label',
        'lbl_contact_id': 'Phone Number or Email Address',
        'lbl_contact_type': 'Type',
        'lbl_contact_notes': 'Notes / Relationship',
        'btn_save_contact': 'Add to Whitelist',
        'tbl_contact_name': 'Name',
        'tbl_contact_id': 'Identifier',
        'tbl_contact_type': 'Type',
        'tbl_contact_added': 'Added On',
        'tbl_contact_actions': 'Actions',
        'no_contacts_empty': 'No trusted contacts added yet.',
        'delete_contact_confirm': 'Are you sure you want to remove this contact from your whitelist?',

        # History Page
        'history_title': 'Security Audit History',
        'history_subtitle': 'Historical log of all analyzed emails and SMS messages',
        'tbl_hist_date': 'Date & Time',
        'tbl_hist_type': 'Type',
        'tbl_hist_sender': 'Sender',
        'tbl_hist_subject': 'Subject / Snippet',
        'tbl_hist_verdict': 'Verdict',
        'tbl_hist_risk': 'Risk',
        'tbl_hist_action': 'Action',
        'view_report_btn': 'View Report',

        # Dashboard Page
        'dash_title': 'Executive Security Dashboard',
        'dash_subtitle': 'Real-time telemetry and threat intelligence across all scans',
        'kpi_total_scans': 'Total Messages Scanned',
        'kpi_spam_detected': 'Spam / Smishing Detected',
        'kpi_safe_messages': 'Safe Communications (Ham)',
        'kpi_critical_threats': 'Critical Security Alerts',
        'chart_verdict_ratio': 'Verdict Distribution',
        'chart_threat_types': 'Identified Threat Types',

        # Extra Result & Component Keys
        'phones_extracted_title': 'Extracted Phone Numbers & Callback Lures',
        'vishing_flagged_badge': 'Vishing / Callback Vectors Flagged',
        'urls_detected_title': 'Detected Hyperlinks',
        'urls_flagged_badge': 'URLs Flagged for Static Inspection',
        'no_urls_badge': 'No Embedded URLs Detected',
        'no_urls_msg': 'This message does not contain any clickable hyperlinks or external URL vectors.',
        'view_orig_msg_btn': 'View Original Message Content & Forensics',
        'link_view_history': '← View Audit History',
        'link_manage_contacts': 'Manage Trusted Contacts →',
        'export_csv': 'Export CSV',
        'no_history_empty': 'No analyzed messages logged yet. Run your first scan from the home page!',
        'history_subtitle_full': 'Immutable security log of analyzed emails, SMS, classification confidence, and URL risk assessments.',
        'dash_hero_badge': 'Threat Telemetry & Risk Metrics',
        'dash_hero_title': 'Security Analytics & Model Metrics',
        'dash_hero_desc': 'Aggregated performance indicators, spam probability distributions, and extracted threat vectors.',
        'kpi_audit_sub': 'Audit log records',
        'kpi_spam_sub': 'malicious/unwanted rate',
        'kpi_ham_sub': 'Verified safe communications',
        'kpi_urls_sub': 'critical risk links',
        'ml_perf_title': 'Supervised Machine Learning Performance',
        'ml_perf_desc': 'Ensemble NLP Classifier (TF-IDF + Multinomial Naive Bayes + Heuristic Defense)',
        'stratified_accuracy_badge': '100% Stratified Test Accuracy',
        'metric_accuracy': 'Accuracy',
        'metric_precision': 'Precision',
        'metric_recall': 'Recall',
        'metric_f1': 'F1-Score',
        'contacts_hero_badge': 'False Positive Defense',
        'contacts_hero_title': 'Trusted Contacts & Sender Whitelist',
        'contacts_hero_desc': 'Messages from people you know (friends, family, colleagues) will never be marked as spam, even if they use casual words like "urgent", "call me", or send links.',
        'contacts_phone_format_tip': 'Phone numbers will match regardless of +91 formatting.',
        'auto_override_active': 'Auto-Override Active',
        'prompt_mark_safe_name': 'Enter a name for this contact (e.g. Rahul Friend, Mom):',

        # Geolocation & Origin Keys
        'geo_card_title': 'Geographic Origin & Threat Vector Map',
        'geo_card_desc': 'Physical location, telecom circle, and web server host country of the message and links',
        'geo_sender_origin': 'Sender Physical Origin',
        'geo_carrier_isp': 'Carrier / Network Host',
        'geo_server_type': 'Source Gateway Type',
        'geo_map_legend_sender': 'Sender Origin',
        'geo_map_legend_url': 'Phishing / Malware Server',
        'geo_map_legend_phone': 'Callback Phone Lure'
    },

    'bn': {
        # Brand & Nav
        'brand_title': 'ইমেল সেন্টিনেল এআই (Sentinel AI)',
        'brand_subtitle': 'স্প্যাম ও সাইবার হুমকি বিশ্লেষক',
        'nav_scan': 'মেসেজ স্ক্যান',
        'nav_dashboard': 'সিকিউরিটি ড্যাশবোর্ড',
        'nav_history': 'অডিট হিস্ট্রি',
        'nav_contacts': 'বিশ্বস্ত পরিচিতি',
        'nav_signin': 'লগইন',
        'nav_register': 'রেজিস্টার',
        'nav_logout': 'লগআউট',
        'db_status_label': 'ডাটাবেস',

        # Hero
        'hero_badge': 'মাল্টি-ভেক্টর নিউরাল প্রোটেকশন ইঞ্জিন',
        'hero_title': 'AI-চালিত স্প্যাম ও সাইবার হুমকি বিশ্লেষণ',
        'hero_desc': 'অত্যাধুনিক মেশিন লার্নিংয়ের সাহায্যে ফিশিং ইমেল, প্রতারণামূলক SMS, ক্ষতিকারক লিঙ্ক ও ভুয়ো সেন্ডার শনাক্ত করুন। কোনো ভুল অ্যালার্ম ছাড়াই বন্ধুবান্ধব বা পরিবারের স্বাভাবিক মেসেজ নিজে থেকেই বুঝতে পারে।',

        # Tabs & Modes
        'tab_email': 'ইমেল মোড (Email Mode)',
        'tab_sms': 'SMS / ফোন মোড (SMS Mode)',
        'presets_label': 'বাস্তব নমুনা পরীক্ষা করে দেখুন:',
        'preset_bank_phish': '১. জরুরি ব্যাঙ্ক ফিশিং',
        'preset_power_smish': '২. বিদ্যুৎ বিল কাটার ভুয়ো SMS',
        'preset_lottery': '৩. লটারি প্রতারণা',
        'preset_friend_chat': '৪. বন্ধুর ব্যক্তিগত চ্যাট (জরুরি কল)',
        'preset_legit_email': '৫. অফিসের স্বাভাবিক ইমেল',

        # Form Inputs
        'lbl_sender': 'প্রেরকের বিবরণ (ইমেল ঠিকানা বা ফোন নম্বর)',
        'lbl_subject': 'বিষয় (Subject Line)',
        'lbl_content': 'মেসেজের মূল অংশ (Message Content)',
        'sender_placeholder_email': 'যেমন: security-alert@secure-bank-verify.com',
        'sender_placeholder_sms': 'যেমন: +91 98765 43210 অথবা VK-HDFCBK',
        'sender_tip_email': 'প্রকৃত প্রাতিষ্ঠানিক বা ব্যক্তিগত ইমেল ঠিকানা',
        'sender_tip_sms': '১০ সংখ্যার মোবাইল নম্বর বা সরকারি TRAI SMS হেডার (যেমন AD-SBIINB)',
        'subject_placeholder': 'যেমন: জরুরি: আপনার অ্যাকাউন্ট এখনই যাচাই করুন',
        'content_placeholder': 'ইমেল বা SMS-এর টেক্সটটি এখানে পেস্ট করুন...',
        'autonomous_sensing_banner': 'স্বয়ংক্রিয় AI উদ্দেশ্য শনাক্তকরণ:',
        'autonomous_sensing_desc': 'কোনো ম্যানুয়াল সেটিংস ছাড়াই বন্ধু বা পরিবারের পরিচিত ভাষার মেসেজ ও সাইবার প্রতারণার পার্থক্য নিজে থেকেই বুঝতে পারে।',
        'preverified_contact_opt': 'পূর্ব-সংরক্ষিত পরিচিতি (ঐচ্ছিক)',
        'btn_analyze_email': 'ইমেল হুমকি বিশ্লেষণ করুন',
        'btn_analyze_sms': 'SMS হুমকি বিশ্লেষণ করুন',
        'scan_footer_note': 'মেসেজের ভাষা, ক্ষতিকারক লিঙ্ক এবং ফোন/হোয়াটসঅ্যাপ কলব্যাক ভেক্টর স্ক্যান করা হয়।',

        # Feature Cards
        'card_sms_title': 'SMS প্রতারণা শনাক্তকরণ',
        'card_sms_desc': 'ভুয়ো বিদ্যুৎ সংযোগ বিচ্ছিন্ন, PAN/KYC ব্লক এবং ব্যক্তিগত মোবাইল থেকে ভুয়ো সরকারি বার্তার সতর্কতা দেয়।',
        'card_phone_title': 'কলব্যাক ও ভিশিং প্রতিরোধ',
        'card_phone_desc': 'প্রতারণামূলক কলব্যাক নম্বর, বিদেশি হাই-রিস্ক কল এবং সন্দেহজনক হোয়াটসঅ্যাপ রিডাইরেকশন শনাক্ত করে।',
        'card_url_title': 'ক্ষতিকারক লিঙ্ক নিরাপত্তা',
        'card_url_desc': 'সন্দেহজনক IP ঠিকানা, ফিশিং ওয়েবসাইট এবং ক্ষতিকারক ডাউনলোড ফাইল (.exe) খতিয়ে দেখে।',
        'card_risk_title': 'ঝুঁকি মাত্রা পরিমাপ',
        'card_risk_desc': 'NLP ল্যাঙ্গুয়েজ মডেল ও সাইবার নিরাপত্তা নিয়মের সমন্বয়ে স্পষ্ট এবং নির্ভরযোগ্য ফলাফল প্রদান করে।',

        # Result Page
        'report_title': 'সাইবার হুমকি বিশ্লেষণ রিপোর্ট',
        'report_subtitle': 'সেন্টিনেল AI দ্বারা প্রস্তুতকৃত বিস্তারিত নিরাপত্তা মূল্যায়ন',
        'btn_back_scan': 'আরেকটি মেসেজ স্ক্যান করুন',
        'verdict_title': 'নিরাপত্তা ফলাফল',
        'spam_probability_label': 'স্প্যাম সম্ভাবনা',
        'overall_risk_title': 'সামগ্রিক ঝুঁকির মাত্রা',
        'threat_meter_title': 'মাল্টি-ভেক্টর থ্রেট মিটার',
        'meter_safe': '০% সম্পূর্ণ নিরাপদ',
        'meter_danger': '১০০% মারাত্মক বিপদ',

        # Result Details
        'threat_type_title': 'শনাক্তকৃত হুমকির ধরন',
        'consequence_title': 'সম্ভাব্য পরিণতি',
        'recommendation_title': 'নিরাপত্তা সংক্রান্ত পরামর্শ',
        'msg_details_title': 'মেসেজের প্রযুক্তিগত তথ্য',
        'col_property': 'বৈশিষ্ট্য',
        'col_value': 'মান',
        'prop_type': 'যোগাযোগের ধরন',
        'prop_sender': 'প্রেরক',
        'prop_subject': 'বিষয়',
        'prop_urls': 'মেসেজে থাকা লিঙ্ক',
        'prop_phones': 'ফোন / হোয়াটসঅ্যাপ নম্বর',
        'prop_ai_override': 'AI সেন্সিং সিদ্ধান্ত',
        'none_detected': 'কোনো হুমকি পাওয়া যায়নি',
        'raw_content_title': 'মেসেজের মূল টেক্সট',

        # URL & Phone Cards
        'urls_analyzed_title': 'মেসেজে থাকা লিঙ্ক বিশ্লেষণ',
        'phones_analyzed_title': 'মেসেজে থাকা ফোন নম্বর বিশ্লেষণ',
        'col_url': 'ওয়েবসাইট লিঙ্ক (URL)',
        'col_url_risk': 'লিঙ্ক ঝুঁকি',
        'col_category': 'হুমকির ধরন',
        'col_reasons': 'চিহ্নিত কারণসমূহ',
        'col_phone': 'ফোন নম্বর',
        'col_country': 'দেশ / উৎস',
        'col_phone_type': 'নম্বরের ধরন',
        'col_phone_risk': 'ঝুঁকির মাত্রা',

        # Banners
        'badge_ai_personal': 'AI নিজস্ব উপলব্ধি',
        'banner_ai_personal': 'স্বয়ংক্রিয় AI শনাক্তকরণ: এটি পরিচিত মানুষের স্বাভাবিক বন্ধুত্বপূর্ণ কথাবার্তা ও চ্যাট। কোনো সাইবার হুমকি বা প্রতারণামূলক লক্ষণ নেই।',
        'banner_whitelist': 'যাচাইকৃত পরিচিত ব্যক্তি: প্রেরক আপনার সংরক্ষিত বিশ্বস্ত তালিকায় রয়েছেন। মেসেজটি নিরাপদ বলে অনুমোদিত।',
        'whitelisted_badge': 'তালিকাভুক্ত',
        'feedback_prompt': 'প্রেরক কি আপনার পরিচিত কেউ (বন্ধু, পরিবারের সদস্য বা সহকর্মী)?',
        'btn_mark_safe': 'পরিচিত ব্যক্তি হিসেবে চিহ্নিত করুন (স্প্যাম নয়)',

        # Contacts Page
        'contacts_title': 'বিশ্বস্ত পরিচিতি ও সেফ-লিস্ট',
        'contacts_subtitle': 'সংরক্ষিত পরিচিতির মেসেজগুলিকে নিরাপদ হিসেবে গণ্য করা হয়, যাতে সাধারণ কথাবার্তায় কোনো ভুল অ্যালার্ম না আসে।',
        'add_contact_title': 'নতুন পরিচিতি যোগ করুন',
        'lbl_contact_name': 'পরিচিতির নাম / পরিচয়',
        'lbl_contact_id': 'ফোন নম্বর বা ইমেল ঠিকানা',
        'lbl_contact_type': 'ধরন',
        'lbl_contact_notes': 'সম্পর্ক / নোট',
        'btn_save_contact': 'তালিকায় যোগ করুন',
        'tbl_contact_name': 'নাম',
        'tbl_contact_id': 'নম্বর / ইমেল',
        'tbl_contact_type': 'ধরন',
        'tbl_contact_added': 'যুক্ত করার তারিখ',
        'tbl_contact_actions': 'পদক্ষেপ',
        'no_contacts_empty': 'এখনও কোনো পরিচিতি যোগ করা হয়নি।',
        'delete_contact_confirm': 'আপনি কি এই পরিচিতিটি তালিকা থেকে মুছে ফেলতে চান?',

        # History Page
        'history_title': 'নিরাপত্তা অডিট হিস্ট্রি',
        'history_subtitle': 'পূর্বে স্ক্যান করা সকল ইমেল ও SMS-এর সংরক্ষিত তালিকা',
        'tbl_hist_date': 'তারিখ ও সময়',
        'tbl_hist_type': 'ধরন',
        'tbl_hist_sender': 'প্রেরক',
        'tbl_hist_subject': 'বিষয় / সংক্ষিপ্ত অংশ',
        'tbl_hist_verdict': 'ফলাফল',
        'tbl_hist_risk': 'ঝুঁকি',
        'tbl_hist_action': 'পদক্ষেপ',
        'view_report_btn': 'রিপোর্ট দেখুন',

        # Dashboard Page
        'dash_title': 'এক্সিকিউটিভ সিকিউরিটি ড্যাশবোর্ড',
        'dash_subtitle': 'সকল স্ক্যানের রিয়েল-টাইম তথ্য ও সাইবার ইন্টেলিজেন্স',
        'kpi_total_scans': 'মোট স্ক্যান করা মেসেজ',
        'kpi_spam_detected': 'স্প্যাম ও প্রতারণা শনাক্ত',
        'kpi_safe_messages': 'নিরাপদ মেসেজ (হাম)',
        'kpi_critical_threats': 'মারাত্মক সাইবার ঝুঁকি',
        'chart_verdict_ratio': 'ফলাফলের অনুপাত',
        'chart_threat_types': 'শনাক্তকৃত হুমকির ধরন',

        # Extra Result & Component Keys
        'phones_extracted_title': 'মেসেজে পাওয়া ফোন নম্বর ও সম্ভাব্য কলব্যাক ফাঁদ',
        'vishing_flagged_badge': 'কলব্যাক / ভিশিং প্রতারণার লক্ষণ চিহ্নিত',
        'urls_detected_title': 'মেসেজে পাওয়া ক্ষতিকারক লিঙ্ক (URLs)',
        'urls_flagged_badge': 'লিঙ্কগুলি নিরাপত্তা বিশ্লেষণের আওতায়',
        'no_urls_badge': 'কোনো ক্ষতিকারক লিঙ্ক নেই',
        'no_urls_msg': 'এই মেসেজে কোনো ক্লিকযোগ্য লিঙ্ক বা ক্ষতিকারক ওয়েবসাইটের সংযোগ নেই।',
        'view_orig_msg_btn': 'মেসেজের মূল টেক্সট ও প্রযুক্তিগত তথ্য দেখুন',
        'link_view_history': '← পূর্ববর্তী অডিট হিস্ট্রি দেখুন',
        'link_manage_contacts': 'বিশ্বস্ত পরিচিতির তালিকা পরিচালনা করুন →',
        'export_csv': 'CSV এক্সপোর্ট করুন',
        'no_history_empty': 'এখনও কোনো মেসেজ রেকর্ড নেই। হোম পেজ থেকে আপনার প্রথম মেসেজ স্ক্যান করুন!',
        'history_subtitle_full': 'পূর্বে স্ক্যান করা সকল ইমেল, SMS, ফিশিং সতর্কতা ও ক্ষতিকারক লিঙ্কের সংরক্ষিত রেকর্ড।',
        'dash_hero_badge': 'সাইবার হুমকি ও সিকিউরিটি মেট্রিক্স',
        'dash_hero_title': 'সিকিউরিটি অ্যানালিটিক্স ও মডেল মেট্রিক্স',
        'dash_hero_desc': 'সকল স্ক্যানিং ডেটা, স্প্যাম সম্ভাবনার অনুপাত এবং সাইবার নিরাপত্তা ঝুঁকির সামগ্রিক পরিসংখ্যান।',
        'kpi_audit_sub': 'মোট অডিট রেকর্ড',
        'kpi_spam_sub': 'ক্ষতিকারক বা স্প্যামের হার',
        'kpi_ham_sub': 'যাচাইকৃত নিরাপদ বার্তা',
        'kpi_urls_sub': 'মারাত্মক ঝুঁকিপূর্ণ লিঙ্ক',
        'ml_perf_title': 'মেশিন লার্নিং মডেলের কর্মক্ষমতা (Performance)',
        'ml_perf_desc': 'উন্নত এনএলপি ক্লাসিফায়ার (TF-IDF + Naive Bayes + নিউরাল হিউরিস্টিক ফিল্টার)',
        'stratified_accuracy_badge': '১০০% সঠিকতা (Test Accuracy)',
        'metric_accuracy': 'সঠিকতা (Accuracy)',
        'metric_precision': 'প্রিসিশন (Precision)',
        'metric_recall': 'রিকল (Recall)',
        'metric_f1': 'এফ১-স্কোর (F1-Score)',
        'contacts_hero_badge': 'ভুল অ্যালার্ম প্রতিরোধ',
        'contacts_hero_title': 'বিশ্বস্ত পরিচিতি ও সেফ-লিস্ট',
        'contacts_hero_desc': 'আপনার পরিচিত ব্যক্তিদের (বন্ধু, পরিবার, সহকর্মী) পাঠানো মেসেজ কখনই ভুল করে স্প্যাম বলে চিহ্নিত হবে না, এমনকি তারা "জরুরি কল কর" বা কোনো লিঙ্ক পাঠালেও।',
        'contacts_phone_format_tip': 'মোবাইল নম্বর +91 কোড সহ বা ছাড়া যেকোনো ফরম্যাটে মিলে যাবে।',
        'auto_override_active': 'স্বয়ংক্রিয় সুরক্ষা সক্রিয়',
        'prompt_mark_safe_name': 'এই পরিচিতির একটি নাম লিখুন (যেমন: বন্ধু রাহুল, মা, দাদা):',

        # Geolocation & Origin Keys
        'geo_card_title': 'মেসেজের ভৌগোলিক উৎস ও সাইবার থ্রেট ম্যাপ',
        'geo_card_desc': 'মেসেজ প্রেরক, টেলিকম সার্কেল এবং ক্ষতিকারক ওয়েব সার্ভারের ভৌগোলিক অবস্থান',
        'geo_sender_origin': 'প্রেরকের ভৌগোলিক উৎস',
        'geo_carrier_isp': 'টেলিকম নেটওয়ার্ক / হোস্টিং',
        'geo_server_type': 'গেটওয়ে / সংযোগের ধরন',
        'geo_map_legend_sender': 'প্রেরকের অবস্থান',
        'geo_map_legend_url': 'ফিশিং / ওয়েব সার্ভার',
        'geo_map_legend_phone': 'কলব্যাক ফাঁদ নম্বর'
    }
}

# Dynamic Risk & Recommendation Localizations (for Bengali output)
DYNAMIC_THREAT_TRANSLATIONS_BN = {
    'UTILITY DISCONNECTION SCAM / VISHING': {
        'type': 'বিদ্যুৎ বা বিল প্রতারণা (Utility Scam / Vishing)',
        'consequence': 'প্রতারকরা বিদ্যুৎ বা সরকারি কর্মকর্তার ভুয়ো পরিচয় দিয়ে ভুক্তভোগীকে ভয় দেখায় এবং টাকা হাতানোর জন্য নির্দিষ্ট নম্বরে কল করতে চাপ দেয়।',
        'recommendation': 'নম্বরটিতে ভুলেও কল করবেন না। বিদ্যুৎ বিভাগ বা সরকার কখনোই ব্যক্তিগত মোবাইল নম্বর থেকে সংযোগ কাটার হুমকি দেয় না।'
    },
    'SMISHING (SMS PHISHING) / KYC FRAUD': {
        'type': 'ব্যাঙ্ক KYC / YONO SMS ফিশিং প্রতারণা',
        'consequence': 'এই SMS-এর মাধ্যমে আপনাকে একটি ভুয়ো ব্যাঙ্কিং লিঙ্কে ক্লিক করতে বা নম্বরে কল করতে বাধ্য করা হয়, যাতে আপনার ব্যাঙ্কের পিন ও OTP চুরি করা যায়।',
        'recommendation': 'লিঙ্কে ক্লিক করবেন না বা কল করবেন না। কোনো ব্যাঙ্ক কখনোই SMS লিঙ্কের মাধ্যমে বা ব্যক্তিগত নম্বরে KYC আপডেট করতে বলে না।'
    },
    'TASK / JOB ADVANCE SCAM': {
        'type': 'পার্ট-টাইম কাজ / ইউটিউব লাইক প্রতারণা',
        'consequence': 'ভুক্তভোগীদের হোয়াটসঅ্যাপ বা টেলিগ্রাম গ্রুপে নিয়ে যাওয়া হয় এবং সহজে আয়ের লোভ দেখিয়ে ধাপে ধাপে টাকা বিনিয়োগের ফাঁদে ফেলা হয়।',
        'recommendation': 'হোয়াটসঅ্যাপ বা টেলিগ্রামে যোগাযোগ করবেন না। কোনো আসল কোম্পানি সোশ্যাল মিডিয়ায় ভিডিও লাইক করার জন্য অগ্রিম টাকা দেয় না।'
    },
    'VISHING / CALLBACK FRAUD': {
        'type': 'কলব্যাক প্রতারণা (Vishing / Phone Trap)',
        'consequence': 'মেসেজের নম্বরে কল করলে প্রতারকরা কৌশলে আপনার গোপন পাসওয়ার্ড, ব্যাঙ্কের তথ্য বা ওটিপি হাতিয়ে নেওয়ার চেষ্টা করবে।',
        'recommendation': 'মেসেজে দেওয়া নম্বরে কল করবেন না। কাস্টমার কেয়ার নম্বর সর্বদা প্রাতিষ্ঠানিক অফিসিয়াল ওয়েবসাইট বা কার্ডের পিছন থেকে যাচাই করুন।'
    },
    'MALWARE': {
        'type': 'ক্ষতিকারক ভাইরাস বা ম্যালওয়্যার (Malware)',
        'consequence': 'এই লিঙ্কটি আপনার ফোনে বা কম্পিউটারে ক্ষতিকারক এক্সিকিউটেবল (.exe/.apk) ফাইল ডাউনলোড করাতে পারে যা আপনার ডিভাইস হ্যাক করতে পারে।',
        'recommendation': 'ফাইলটি ডাউনলোড করবেন না। সাথে সাথে মেসেজটি মুছে ফেলুন এবং ফোনে অ্যান্টিভাইরাস স্ক্যান চালান।'
    },
    'CREDENTIAL THEFT': {
        'type': 'পাসওয়ার্ড ও তথ্য চুরি (Credential Theft)',
        'consequence': 'এই লিঙ্কটি একটি নকল লগইন পেজে নিয়ে যায়, যা আপনার আসল পাসওয়ার্ড ও ইউজারনেম চুরি করার উদ্দেশ্যে তৈরি।',
        'recommendation': 'কোনো পাসওয়ার্ড প্রবেশ করাবেন না। অচেনা মেসেজ থেকে আসা লিঙ্কে কখনোই লগইন করবেন না।'
    },
    'PHISHING': {
        'type': 'ফিশিং আক্রমণ (Phishing Attack)',
        'consequence': 'একটি জাল ওয়েবসাইটের মাধ্যমে আপনার ব্যক্তিগত তথ্য ও অ্যাকাউন্ট ডিটেইলস হাতানোর চেষ্টা করা হচ্ছে।',
        'recommendation': 'লিঙ্কে ক্লিক করবেন না। ব্রাউজারে সরাসরি আসল অফিসিয়াল ওয়েবসাইটে প্রবেশ করুন।'
    },
    'FINANCIAL FRAUD / LOTTERY SCAM': {
        'type': 'আর্থিক লটারি ও পুরস্কারের প্রতারণা',
        'consequence': 'লটারি বা পুরস্কারের টাকা ছাড়ানোর নাম করে প্রতারকরা প্রসেসিং ফি বাবদ আপনার কাছ থেকে টাকা হাতানোর চেষ্টা করছে।',
        'recommendation': 'টাকা পাঠাবেন না বা কল করবেন না। কোনো আসল লটারি পুরস্কার দেওয়ার জন্য অগ্রিম টাকা চায় না।'
    },
    'SUSPICIOUS URL / PHISHING': {
        'type': 'সন্দেহজনক ক্ষতিকারক লিঙ্ক',
        'consequence': 'এই লিঙ্কটিতে একাধিক সন্দেহজনক লক্ষণ রয়েছে যা বিপজ্জনক ওয়েব পেজে নিয়ে যেতে পারে।',
        'recommendation': 'লিঙ্কটিতে প্রবেশ করা থেকে বিরত থাকুন এবং প্রেরককে ব্লক করুন।'
    },
    'UNSOLICITED SPAM': {
        'type': 'অনাকাঙ্ক্ষিত স্প্যাম মেসেজ',
        'consequence': 'বাণিজ্যিক বা প্রচারণামূলক অপ্রয়োজনীয় বার্তা।',
        'recommendation': 'স্প্যাম হিসেবে চিহ্নিত করুন এবং কোনো উত্তর দেবেন না।'
    },
    'PERSONAL PEER COMMUNICATION / SAFE': {
        'type': 'স্বাভাবিক ব্যক্তিগত চ্যাট / সম্পূর্ণ নিরাপদ',
        'consequence': 'মেসেজটিতে সাধারণ মানবিক কথাবার্তার ভাষা রয়েছে। কোনো ফিশিং বা সাইবার হুমকির লক্ষণ মেলেনি।',
        'recommendation': 'যোগাযোগ করা নিরাপদ। এটি একটি খাঁটি ব্যক্তিগত বার্তা।'
    },
    'VERIFIED KNOWN CONTACT / SAFE': {
        'type': 'যাচাইকৃত বিশ্বস্ত পরিচিতি / নিরাপদ',
        'consequence': 'মেসেজটি আপনার বিশ্বস্ত তালিকার পরিচিত ব্যক্তির থেকে এসেছে। কোনো ক্ষতিকারক ফাইল মেলেনি।',
        'recommendation': 'যোগাযোগ করা সম্পূর্ণ নিরাপদ।'
    }
}

RISK_LEVEL_TRANSLATIONS_BN = {
    'CRITICAL': '🔴 মারাত্মক ঝুঁকি (Critical)',
    'HIGH': '🟠 উচ্চ ঝুঁকি (High)',
    'MEDIUM': '🟡 মাঝারি ঝুঁকি (Medium)',
    'LOW': '🟢 কম ঝুঁকি (Low)',
    'VERY LOW': '🟢 খুব কম ঝুঁকি (Very Low / Safe)'
}

CLASSIFICATION_TRANSLATIONS_BN = {
    'SPAM': 'স্প্যাম (SPAM)',
    'HAM': 'নিরাপদ / আসল (HAM)'
}

def t(key, lang='en', default=None):
    """Fetches localized string for the specified key and language."""
    catalog = TRANSLATIONS.get(lang, TRANSLATIONS['en'])
    if key in catalog:
        return catalog[key]
    # Fallback to English
    return TRANSLATIONS['en'].get(key, default or key)

def localize_risk_result(overall_risk, lang='en'):
    """Returns a localized copy of overall_risk dict when Bengali is selected."""
    if lang != 'bn' or not overall_risk:
        return overall_risk
    
    localized = dict(overall_risk)
    r_type = overall_risk.get('risk_type', '')
    r_level = overall_risk.get('risk_level', '')
    
    # Check if exact or partial match in dynamic dict
    matched_trans = None
    for eng_key, trans in DYNAMIC_THREAT_TRANSLATIONS_BN.items():
        if eng_key in r_type:
            matched_trans = trans
            break
            
    if matched_trans:
        localized['risk_type'] = matched_trans['type']
        localized['possible_consequence'] = matched_trans['consequence']
        localized['recommendation'] = matched_trans['recommendation']

    if r_level in RISK_LEVEL_TRANSLATIONS_BN:
        localized['risk_badge'] = RISK_LEVEL_TRANSLATIONS_BN[r_level]

    return localized
